### ISSUE TITLE
docs bug: disappearing navigation

### ISSUE THREAD

**Issue by AnjaMis** [axone-protocol/docs#566]
When opening any item on the left from the navbar, the complete navigation disappears and only the items from that category are visible. To see the whole navigation, the user needs to return to homepage. 

Screenshots home page:

![Image](https://github.com/user-attachments/assets/281e6583-f210-4555-b1be-8d2af38b7fa7)

Screenshot example FAQ page (nav on the left not visible anymore)

![Image](https://github.com/user-attachments/assets/55c51f68-b718-4abd-ac0f-2fe07d0cdd50)

cc @ccamel @JulienMassonnat

**Comment by ccamel** [comment]
Still relevant @AnjaMis?

**Comment by AnjaMis** [comment]
no, this has been done!
